language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=placentagen
