language: python
sudo: false
dist: trusty
python:
  - "3.6"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install -U numpy
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=placentagen
