language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "3.6"
install:
  - pip install nose coverage
  - python setup.py develop
  - pip install scipy
script:
  - nosetests --with-coverage --cover-package=placentagen
